### ISSUE TITLE
LinkedIn.com craches

### ISSUE THREAD

**Issue by ruud2005** [usnistgov/Metrology#1]
The page crashes with the extension enabled when opening https://www.linkedin.com , even after adding it to the whitelist. Extension de-activated all is fine.
Chrome Version 75.0.3770.142 (Windows10)

**Comment by dwf-NIST** [comment]
LinkedIn works for me.
1. Please check the extension log to confirm that it actually killed www.linkedin.com and not something else that happened to cause that tab to crash.
2.  If it was www.linkedin.com, please ensure that the hostname is entered just like that in the whitelist, not including https:// or anything else.
