### ISSUE TITLE
The Chrome Reaper terminates pages on profiles without extension installed

### ISSUE THREAD

**Issue by itsknob** [usnistgov/Metrology#2]
I have two profiles ("people") on Chrome that I generally use simultaneously (separate windows). I have installed The Chrome Reaper in one profile, but not in the other. I opened an intensive page in the profile without the extension installed on it, and the page was terminated by the extension. I received the notification for it on the profile with the extension installed.

I believe this is separate from the Known Issue of: "Errors are reported when switching to a different Chrome profile or entering/leaving incognito mode." That appears to be related to actually switching into another profile.

Steps to recreate:
1. Create Two Chrome Profiles/People
1. Install the Extension in one profile, but not the other.
1. Open both profiles (separate windows)
1. Open an intensive page (In my case [Youtube TV](https://tv.youtube.com))
1. New Page is terminated due to high CPU Usage by Chrome Process
1. Observe Notification in Chrome window with extension installed.

Actions: 
I understand that the purpose of this Extension is to monitor Chrome processes and that this separate profile is another chrome processes, but I believe there should, at a minimum, be some mention of this behavior in the README.

I believe this may include possible issues when running multiple versions of chrome concurrently, IE. Canary, Chromium Source, etc., but I have not tested this.

**Comment by dwf-NIST** [comment]
Agreed that the behavior should be documented if not changed.  I will look into the cross-profile behavior and see if there is a better way before just documenting.

**Comment by dwf-NIST** [comment]
The processes API does not enforce profile and incognito mode isolation.  Other APIs do; e.g., Reaper is prevented from determining the URL associated with a tab in another profile.  This inconsistency was the cause of previously observed quirks.

It isn't obvious that the enforcement of these boundaries belongs in Reaper, nor is there an obvious right way to do it, so I have documented the problem and handled the errors that were resulting.
